from sympy.combinatorics.named_groups import SymmetricGroup
from sympy.combinatorics import Permutation, PermutationGroup
from sympy.combinatorics.fp_groups import CosetTable

class Group():
	
	def __init__(self, G):
		assert G.is_group
		self.G = G
	
	def __truediv__(self, N):
		print("div")
		print(g.G.elements)
		print(N.G.elements)
		coset = self.G.coset_transversal(N.G)
		p = self.G.identity
		for e in self.G.coset_transversal(N.G):
			print("a",(p*e).array_form)	
			print("b",(p*e*e).array_form)
		quotientGroup = Group(PermutationGroup(coset))
		print("coset", coset)
		print("quotient group", quotientGroup.elements())
		print("main group", self.elements())
		print(self.G.equals(Group(PermutationGroup(coset))))
		cst = CosetTable(self.G, N.G)
		print(cst.table)		
		return Group(PermutationGroup(coset))

	def elements(self):
		return self.G.elements

	def is_element(self, e):
		return self.G.contains(e)

	def equals(self, H):
		assert isinstance(H, self.__class__)
		return self.G.equals(H.G)

	def __repr__(self):
		
		return "Group generated by: "+ str(self.G.generators) 

class S1(Group):
	def __init__(self):
		super(S1, self).__init__(SymmetricGroup(1))

	def perm_name(self, p):
		assert self.G.contains(p)
		if p == self.G.identity:
			return "e"

class S2(Group):
	def __init__(self):
		super(S2, self).__init__(SymmetricGroup(2))

	def perm_name(self, p):
		assert self.G.contains(p)
		if p == self.G.identity:
			return "e"
		else:
			return "r"
class S3(Group):
	def __init__(self):
		super(S3, self).__init__(SymmetricGroup(3))

	def perm_name(self, p):
		assert self.G.contains(p)
		rank_list = {0: "e", 1: "r", 2:"rot^2r", 3: "rot^2", 4: "rot", 5: "rotr"}
		return rank_list[p.rank()]

class S4(Group):	

	def __init__(self):
		super(S4, self).__init__(SymmetricGroup(4))


if __name__== "__main__":
	g = S3() 
	print(g.perm_name(Permutation([0,2,1])))
	p = Permutation([0,2,1])
	g3 = g.G.subgroup([p])
	print(g.G.coset_factor(p))
	
	perm = PermutationGroup([p])
	N= Group(perm)
	print("N elements")
	print(N.elements())
	quot = g/N
	print( "Quotient group",quot.elements())
	tet = Group(SymmetricGroup(4))
	print("gen tet:",tet.G.generators)
	
	for e in g.G.elements:
		print(p*e)	
